from .auth import RegistrateUserSchema, LoginUserSchema, UserActionResponseSchema, StatusResponseSchema, UserPayload
# from .hhvacancy import HHVacancySearchSchema, HHVacancySearchResponseSchema, HHVacancyShortSchema, HHVacancySearchResponseSchema
from .vacancy import VacancySearchSchema, VacancyShortSchema, VacancySearchResponseSchema, VacancySearchWithUserResponseSchema
from .request import RequestResponseSchema
from .ai.get_stack_by_profession import GetStackByProfessionRequestSchema, GetStackByProfessionResponseSchema 
from .ai.write_questions_by_stack import GetQuestionsByStackRequestSchema, GetQuestionsByStackResponseSchema